build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables:
    EXECUTOR: /kaniko/executor --context "${CI_PROJECT_DIR}"
  script:
    - echo "${CI_REGISTRY_IMAGE}"
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - "${EXECUTOR} --dockerfile ${CI_PROJECT_DIR}/ubuntu/Dockerfile --destination ${CI_REGISTRY_IMAGE}/ubuntu:${CI_COMMIT_TAG}"
    - "${EXECUTOR} --dockerfile ${CI_PROJECT_DIR}/ubuntu-python3.8/Dockerfile --build-arg \"PYTHON=python3.8\" --destination ${CI_REGISTRY_IMAGE}/ubuntu-python3.8:${CI_COMMIT_TAG}"
    - "${EXECUTOR} --dockerfile ${CI_PROJECT_DIR}/almalinux/Dockerfile --destination ${CI_REGISTRY_IMAGE}/almalinux:${CI_COMMIT_TAG}"
  only:
    - master

